FROM public.ecr.aws/lambda/provided:al2023

# Copy bootstrap script if exists, otherwise create default
COPY script-helpers/shell/native/bootstrap ${LAMBDA_TASK_ROOT}/bootstrap

COPY platform-lambda/build/native/nativeCompile/* ${LAMBDA_TASK_ROOT}/

RUN chmod +x ${LAMBDA_TASK_ROOT}/platform-lambda

ENTRYPOINT ["/var/task/bootstrap"]
